name: ci

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn config set ignore-engines true
          yarn --frozen-lockfile
      - name: Run tests
        run: yarn test:coverage --verbose=false
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
